name = "kth-calendar-proxy"
main = "src/index.ts"
compatibility_date = "2023-05-07"

[[kv_namespaces]]
binding = "CALENDAR"
id = "807e96c9979c4a77a795df3b1091a31e"
preview_id = "807e96c9979c4a77a795df3b1091a31e"
